# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x0btodoPackage\"\t\n\x07noParam\"\x18\n\x08TodoText\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x08TodoItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"1\n\tTodoItems\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.todoPackage.TodoItem2}\n\x04Todo\x12:\n\ncreateTodo\x12\x15.todoPackage.TodoText\x1a\x15.todoPackage.TodoItem\x12\x39\n\treadTodos\x12\x14.todoPackage.noParam\x1a\x16.todoPackage.TodoItemsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOPARAM']._serialized_start=27
  _globals['_NOPARAM']._serialized_end=36
  _globals['_TODOTEXT']._serialized_start=38
  _globals['_TODOTEXT']._serialized_end=62
  _globals['_TODOITEM']._serialized_start=64
  _globals['_TODOITEM']._serialized_end=100
  _globals['_TODOITEMS']._serialized_start=102
  _globals['_TODOITEMS']._serialized_end=151
  _globals['_TODO']._serialized_start=153
  _globals['_TODO']._serialized_end=278
# @@protoc_insertion_point(module_scope)
